@host = http://localhost:3000

### Create Driver
POST {{host}}/drivers
Content-Type: application/json

{
    "licenseId": "ABC123456",
    "firstName": "John",
    "surname": "Doe"
}

### Fetch Driver
GET {{host}}/drivers/ABC123456

### Fetch Drivers
GET {{host}}/drivers/?limit=2&page=1

### Update Driver
PUT {{host}}/drivers/ABC123456
Content-Type: application/json

{
    "firstName": "Jane",
    "surname": "Doe",
    "secondName": "Emily",
    "secondSurname": "Johnson"
}

### Delete Driver
DELETE {{host}}/drivers/ABC123456
Content-Type: application/json
