@host = http://localhost:3000

### GET request to server root
GET {{host}}/

### Create Vehicle
POST {{host}}/vehicles
Content-Type: application/json

{
    "number": "VIN-example",
    "brand": "Toyota",
    "model": "Camry"
}

### Fetch Vehicle
GET {{host}}/vehicles/VIN-example

### Fetch Vehicles
GET {{host}}/vehicles/?limit=2&page=2
