@host = http://localhost:3000

### GET request to server root
GET {{host}}/

### Create Vehicle
POST {{host}}/vehicles
Content-Type: application/json

{
    "number": "VIN-example",
    "brand": "Toyota",
    "model": "Camry"
}
